# Generated by Django 5.0.6 on 2024-06-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('payment_id', models.CharField(max_length=100)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_amount', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('shipment_id', models.CharField(max_length=100)),
                ('shipment_status', models.BooleanField(default=False)),
                ('shipment_method', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
